### ISSUE TITLE
Some search content is missing

### ISSUE THREAD

**Issue by cary-rowen** [ibrahim-s/searchWith#3]
Press: NVDA+windows+s, Then type "C#" in the input box.
Using the default Google search, you will find that "#" is missing.
I think this may be related to the escaping of regular expressions. I didn’t look at the code, so I raised an issue first.
You should also consider other similar situations, such as "C++".

Thanks.

**Comment by ibrahim-s** [comment]
Hello Rowen
Yes, you are right
there is a problem in this region
really the hash sign(#) is used in the url
to direct the url to a specific place in the webpage.
and even if we enter in the search box for instance #python
the google search webpage will open, with an empty query.
and you are right also for other characters like the plus sign.
I think really we should escape the query string before putting it in the url.
not really regular expressions, but escaping special characters in the url.
for instance the hash sign will be replaced with %32, and so on.
I think for now we have to use urllib.parse.quote function to solve this.
I will inspect that, and try to deal with it.
thank you Rowen
I greet you really

**Comment by ibrahim-s** [comment]
Hi @cary-rowen 
would you please test this version:
[searchWith-1.5-dev](https://ci.appveyor.com/api/buildjobs/epufdpt9lxnhm3os/artifacts/searchWith-1.5-dev.nvda-addon)
I think the bug has been fixed.
would you confirm that please
Thank you

**Comment by cary-rowen** [comment]
Hi, @ibrahim-s 
Thank you very much for your patience and results. I tested it and the experience is good so far.
I will close this issue.

**Comment by ibrahim-s** [comment]
OK, great
Thank you for your contributions and help and activity.
greetings
